FROM java:8
ADD reference-api-webapp/target/hspc-reference-api-webapp*.jar app.jar
ADD docker/test/wrapper.sh wrapper.sh
RUN bash -c 'chmod +x /wrapper.sh'
RUN bash -c 'touch /app.jar'
ENTRYPOINT ["/bin/bash", "wrapper.sh"]
