--
--  * #%L
--  *
--  * %%
--  * Copyright (C) 2014-2019 Healthcare Services Platform Consortium
--  * %%
--  * Licensed under the Apache License, Version 2.0 (the "License");
--  * you may not use this file except in compliance with the License.
--  * You may obtain a copy of the License at
--  *
--  *      http://www.apache.org/licenses/LICENSE-2.0
--  *
--  * Unless required by applicable law or agreed to in writing, software
--  * distributed under the License is distributed on an "AS IS" BASIS,
--  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--  * See the License for the specific language governing permissions and
--  * limitations under the License.
--  * #L%
--

SET FOREIGN_KEY_CHECKS = 0;

USE hspc_8_hspc9;

CREATE TEMPORARY TABLE IF NOT EXISTS schema_to_migrate AS (
  SELECT schema_name FROM information_schema.SCHEMATA WHERE UPPER(schema_name) LIKE 'HSPC_8%'
);

DROP PROCEDURE IF EXISTS MIGRATE_HAPI_37_TO_HAPI_38;

DELIMITER //
CREATE PROCEDURE MIGRATE_HAPI_37_TO_HAPI_38
(IN MYSCHEMANAME VARCHAR(255))

BEGIN
  DECLARE SQLStmt TEXT;

  SELECT CONCAT('Migrating schema: ', MYSCHEMANAME, '...') as status;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_FORCED_ID DROP INDEX IDX_FORCEDID_TYPE_FID');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_FORCED_ID engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('CREATE UNIQUE INDEX IDX_FORCEDID_TYPE_FID ON ', MYSCHEMANAME, '.HFJ_FORCED_ID (RESOURCE_TYPE, FORCED_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_FORCED_ID add constraint FK_FORCEDID_RESOURCE foreign key (RESOURCE_PID) references ', MYSCHEMANAME, '.HFJ_RESOURCE (RES_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_HISTORY_TAG engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_HISTORY_TAG add constraint FK_HISTORYTAG_HISTORY foreign key (RES_VER_PID) references ', MYSCHEMANAME,  '.HFJ_RES_VER (PID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_HISTORY_TAG add constraint FKtderym7awj6q8iq5c51xv4ndw foreign key (TAG_ID) references ', MYSCHEMANAME, '.HFJ_TAG_DEF (TAG_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_IDX_CMP_STRING_UNIQ modify IDX_STRING varchar(200) not null');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_IDX_CMP_STRING_UNIQ engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_IDX_CMP_STRING_UNIQ add constraint FK_IDXCMPSTRUNIQ_RES_ID foreign key (RES_ID) references ', MYSCHEMANAME, '.HFJ_RESOURCE (RES_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RESOURCE drop column RES_TITLE');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RESOURCE engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RESOURCE add constraint FKhjgj8cp879gfxko25cx5o692r foreign key (FORCED_ID_PID) references ', MYSCHEMANAME, '.HFJ_FORCED_ID (PID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RES_LINK alter column SOURCE_RESOURCE_TYPE drop default');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RES_LINK alter column TARGET_RESOURCE_TYPE drop default');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RES_LINK engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RES_LINK add constraint FK_RESLINK_SOURCE foreign key (SRC_RESOURCE_ID) references ', MYSCHEMANAME, '.HFJ_RESOURCE (RES_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RES_LINK add constraint FK_RESLINK_TARGET foreign key (TARGET_RESOURCE_ID) references ', MYSCHEMANAME, '.HFJ_RESOURCE (RES_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RES_PARAM_PRESENT engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RES_PARAM_PRESENT add constraint FK_RESPARMPRES_RESID foreign key (RES_ID) references ', MYSCHEMANAME, '.HFJ_RESOURCE (RES_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RES_REINDEX_JOB modify SUSPENDED_UNTIL datetime null');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RES_REINDEX_JOB modify UPDATE_THRESHOLD_HIGH datetime not null');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RES_REINDEX_JOB modify UPDATE_THRESHOLD_LOW datetime null');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RES_TAG engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RES_TAG add constraint FK_RESTAG_RESOURCE foreign key (RES_ID) references ', MYSCHEMANAME, '.HFJ_RESOURCE (RES_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RES_TAG add constraint FKbfcjbaftmiwr3rxkwsy23vneo foreign key (TAG_ID) references ', MYSCHEMANAME, '.HFJ_TAG_DEF (TAG_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RES_VER modify RES_ENCODING varchar(5) not null');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RES_VER drop column RES_TITLE');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RES_VER engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_RES_VER add constraint FKh20i7lcbchkaxekvwg9ix4hc5 foreign key (FORCED_ID_PID) references ', MYSCHEMANAME, '.HFJ_FORCED_ID (PID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SEARCH modify SEARCH_UUID varchar(36) not null');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SEARCH engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SEARCH_INCLUDE engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SEARCH_INCLUDE add constraint FK_SEARCHINC_SEARCH foreign key (SEARCH_PID) references ', MYSCHEMANAME, '.HFJ_SEARCH (PID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('DROP TABLE ', MYSCHEMANAME, '.HFJ_SEARCH_PARM');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SEARCH_RESULT engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SEARCH_RESULT add constraint FK_SEARCHRES_RES foreign key (RESOURCE_PID) references ', MYSCHEMANAME, '.HFJ_RESOURCE (RES_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SEARCH_RESULT add constraint FK_SEARCHRES_SEARCH foreign key (SEARCH_PID) references ', MYSCHEMANAME, '.HFJ_SEARCH (PID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SPIDX_COORDS engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SPIDX_COORDS add constraint FKc97mpk37okwu8qvtceg2nh9vn foreign key (RES_ID) references ', MYSCHEMANAME, '.HFJ_RESOURCE (RES_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SPIDX_DATE drop index IDX_SP_DATE');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SPIDX_DATE engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SPIDX_DATE add constraint FK17s70oa59rm9n61k9thjqrsqm foreign key (RES_ID) references ', MYSCHEMANAME, '.HFJ_RESOURCE (RES_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SPIDX_NUMBER engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SPIDX_NUMBER add constraint FKcltihnc5tgprj9bhpt7xi5otb foreign key (RES_ID) references ', MYSCHEMANAME, '.HFJ_RESOURCE (RES_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SPIDX_QUANTITY drop column HASH_UNITS_AND_VALPREFIX');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SPIDX_QUANTITY drop column HASH_VALPREFIX');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SPIDX_QUANTITY engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SPIDX_QUANTITY add constraint FKn603wjjoi1a6asewxbbd78bi5 foreign key (RES_ID) references ', MYSCHEMANAME, '.HFJ_RESOURCE (RES_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SPIDX_STRING engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('CREATE INDEX IDX_SP_STRING_HASH_IDENT ON ', MYSCHEMANAME, '.HFJ_SPIDX_STRING (HASH_IDENTITY)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SPIDX_STRING add constraint FK_SPIDXSTR_RESOURCE foreign key (RES_ID) references ', MYSCHEMANAME, '.HFJ_RESOURCE (RES_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SPIDX_TOKEN engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SPIDX_TOKEN add constraint FK7ulx3j1gg3v7maqrejgc7ybc4 foreign key (RES_ID) references ', MYSCHEMANAME, '.HFJ_RESOURCE (RES_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SPIDX_URI engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SPIDX_URI add constraint FKgxsreutymmfjuwdswv3y887do foreign key (RES_ID) references ', MYSCHEMANAME, '.HFJ_RESOURCE (RES_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SUBSCRIPTION_STATS engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_SUBSCRIPTION_STATS add constraint FK_SUBSC_RESOURCE_ID foreign key (RES_ID) references ', MYSCHEMANAME, '.HFJ_RESOURCE (RES_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_TAG_DEF drop column myHashCode');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.HFJ_TAG_DEF engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('DROP TABLE ', MYSCHEMANAME, '.SEQ_SEARCHPARM_ID');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CODESYSTEM engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CODESYSTEM add constraint FK_TRMCODESYSTEM_CURVER foreign key (CURRENT_VERSION_PID) references ', MYSCHEMANAME, '.TRM_CODESYSTEM_VER (PID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CODESYSTEM add constraint FK_TRMCODESYSTEM_RES foreign key (RES_ID) references ', MYSCHEMANAME, '.HFJ_RESOURCE (RES_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CODESYSTEM_VER engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CODESYSTEM_VER add constraint FK_CODESYSVER_CS_ID foreign key (CODESYSTEM_PID) references ', MYSCHEMANAME, '.TRM_CODESYSTEM (PID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CODESYSTEM_VER add constraint FK_CODESYSVER_RES_ID foreign key (RES_ID) references ', MYSCHEMANAME, '.HFJ_RESOURCE (RES_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT add constraint FK_CONCEPT_PID_CS_PID foreign key (CODESYSTEM_PID) references ', MYSCHEMANAME, '.TRM_CODESYSTEM_VER (PID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT_DESIG engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT_DESIG add constraint FK_CONCEPTDESIG_CONCEPT foreign key (CONCEPT_PID) references ', MYSCHEMANAME, '.TRM_CONCEPT (PID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT_DESIG add constraint FK_CONCEPTDESIG_CSV foreign key (CS_VER_PID) references ', MYSCHEMANAME, '.TRM_CODESYSTEM_VER (PID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT_MAP engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT_MAP add constraint FK_TRMCONCEPTMAP_RES foreign key (RES_ID) references ', MYSCHEMANAME, '.HFJ_RESOURCE (RES_ID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;


  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT_MAP_GROUP engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT_MAP_GROUP add constraint FK_TCMGROUP_CONCEPTMAP foreign key (CONCEPT_MAP_PID) references ', MYSCHEMANAME, '.TRM_CONCEPT_MAP (PID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT_MAP_GRP_ELEMENT engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('CREATE INDEX IDX_CNCPT_MAP_GRP_CD ON ', MYSCHEMANAME, '.TRM_CONCEPT_MAP_GRP_ELEMENT (SOURCE_CODE)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT_MAP_GRP_ELEMENT add constraint FK_TCMGELEMENT_GROUP foreign key (CONCEPT_MAP_GROUP_PID) references ', MYSCHEMANAME, '.TRM_CONCEPT_MAP_GROUP (PID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT_MAP_GRP_ELM_TGT engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('CREATE INDEX IDX_CNCPT_MP_GRP_ELM_TGT_CD ON ', MYSCHEMANAME, '.TRM_CONCEPT_MAP_GRP_ELM_TGT (TARGET_CODE)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT_MAP_GRP_ELM_TGT add constraint FK_TCMGETARGET_ELEMENT foreign key (CONCEPT_MAP_GRP_ELM_PID) references ', MYSCHEMANAME, '.TRM_CONCEPT_MAP_GRP_ELEMENT (PID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT_PC_LINK engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT_PC_LINK add constraint FK_TERM_CONCEPTPC_CHILD foreign key (CHILD_PID) references ', MYSCHEMANAME, '.TRM_CONCEPT (PID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT_PC_LINK add constraint FK_TERM_CONCEPTPC_CS foreign key (CODESYSTEM_PID) references ', MYSCHEMANAME, '.TRM_CODESYSTEM_VER (PID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT_PC_LINK add constraint FK_TERM_CONCEPTPC_PARENT foreign key (PARENT_PID) references ', MYSCHEMANAME, '.TRM_CONCEPT (PID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT_PROPERTY engine=InnoDB');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT_PROPERTY add constraint FK_CONCEPTPROP_CONCEPT foreign key (CONCEPT_PID) references ', MYSCHEMANAME, '.TRM_CONCEPT (PID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SET @SQLStmt = CONCAT('ALTER TABLE ', MYSCHEMANAME, '.TRM_CONCEPT_PROPERTY add constraint FK_CONCEPTPROP_CSV foreign key (CS_VER_PID) references ', MYSCHEMANAME, '.TRM_CODESYSTEM_VER (PID)');
  PREPARE Stmt FROM @SQLStmt;
  EXECUTE Stmt;
  DEALLOCATE PREPARE Stmt;

  SELECT CONCAT('Migrating schema: ', MYSCHEMANAME, ' complete');

END //
DELIMITER ;

DROP PROCEDURE IF EXISTS DO_MIGRATE_HAPI_37_TO_HAPI_38;

DELIMITER //
CREATE PROCEDURE DO_MIGRATE_HAPI_37_TO_HAPI_38() BEGIN
  DECLARE done BOOLEAN DEFAULT FALSE;
  DECLARE current_schema_name VARCHAR(255);
  DECLARE cur CURSOR FOR SELECT schema_name FROM information_schema.SCHEMATA WHERE UPPER(schema_name) LIKE 'HSPC_8%';
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET done := TRUE;
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42S22' BEGIN END;
  DECLARE CONTINUE HANDLER FOR SQLSTATE '42000' BEGIN END;

  OPEN cur;

  testLoop: LOOP
    FETCH cur INTO current_schema_name;
    IF done THEN
      LEAVE testLoop;
    END IF;
    CALL MIGRATE_HAPI_37_TO_HAPI_38(current_schema_name);
  END LOOP testLoop;

  CLOSE cur;
END //
DELIMITER ;

CALL DO_MIGRATE_HAPI_37_TO_HAPI_38();

SET FOREIGN_KEY_CHECKS = 1;

