ALTER TABLE HFJ_RESOURCE DROP COLUMN RES_TEXT;
ALTER TABLE HFJ_RESOURCE DROP COLUMN RES_ENCODING;
-- ALTER TABLE hfj_res_ver ALTER COLUMN res_encoding DROP NOT NULL;
ALTER TABLE HFJ_RES_VER MODIFY RES_ENCODING VARCHAR(5) NULL;
-- ALTER TABLE hfj_res_ver ALTER COLUMN res_text DROP NOT NULL;
ALTER TABLE HFJ_RES_VER MODIFY COLUMN RES_TEXT LONGBLOB NULL;
