# Platform Servers
hspc:
  platform:
    api:
      oauth2:
        clientSecret: secret
      fhir:
        db:
          host: jdbc:mysql://sandboxdb.hspconsortium.org:3306
          username: system
          password: ENC(lA/Ifn1Cm6pYGGydIXNQIa6n7ryn5A1+)
        terminology:
          proxy:
            host: api-v5-stu3.hspconsortium.org/term01
            contextPath: /open
    authorization:
      url: https://auth.hspconsortium.org
    messaging:
      protocol: http
      subscriptionSupport:
        enabled: false

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES
