# Platform Servers
hspc:
  platform:
    api:
      oauth2:
        clientSecret: secret
      fhir:
        db:
          host: jdbc:mysql://db-test.hspconsortium.org:3306
          password: ENC(PGbAqA2yTasSehiLRk60NpQLMQ1btRtID+8hvhWf9AI=)
        datasource:
          cache:
            size: 5
        terminology:
          proxy:
            host: api-v5-stu3.hspconsortium.org/term01
            contextPath: /open
    authorization:
      url: https://auth-test.hspconsortium.org
    messaging:
      protocol: http
      host: messaging-test.hspconsortium.org
      subscriptionSupport:
        enabled: false

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES
