hibernate:
  search:
    default:
      indexBase: /var/indexes/@artifact.name@

# Platform Servers
hspc:
  platform:
    api:
      oauth2:
        clientSecret: secret
      fhir:
        db:
          host: db-test.hspconsortium.org
          username: reference_api
          password: ENC(VlyuolSSom0UHkxBTlmTl76QM4W7mn87zjTAvqYIrZQ=)
        datasource:
          cache:
            size: 5
    authorization:
      url: https://auth-test.hspconsortium.org

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES