# Platform Servers
hspc:
  platform:
    api:
      oauth2:
        clientSecret: secret
      fhir:
        db:
          host: sandboxdb.hspconsortium.org
          username: system
          password: ENC(LfMhv9cr1C3MRuCwBPI80EJAEGP9L4R5)
    authorization:
      url: https://auth.hspconsortium.org
    messaging:
      pubsub:
        enabled: true
        forSandboxes: travisdstu2,PulmonaryEmbolism,noman_dstu2,nomanstu3
        subscription:
          channel:
            endpoint: https://sandbox.hspconsortium.org/hspc5/sandbox/echo
#          forResources: Patient,Observation,Allergy

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES

---

spring:
  profiles: dstu2

hspc:
  platform:
    api:
      fhir:
        hibernate:
          indexSourceUrl: https://content.hspconsortium.org/datasets/reference-api/hspc_5/indexes_hspc_5_dstu2.tar.gz

hibernate:
  search:
    default:
      indexBase: /var/indexes/@artifact.name@/dstu2

---

spring:
  profiles: stu3

hspc:
  platform:
    api:
      fhir:
        hibernate:
          indexSourceUrl: https://content.hspconsortium.org/datasets/reference-api/hspc_5/indexes_hspc_5_stu3.tar.gz

hibernate:
  search:
    default:
      indexBase: /var/indexes/@artifact.name@/stu3
