server:
  port: 8075
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto

spring:
  application:
    name: HSPC Reference API
  profiles:
    active: multitenant,stu3
  datasource:
    initialSize: 1
    maxActive: 5

hibernate:
  search:
    default:
      indexBase: target/@artifact.name@/lucenefiles

logging:
  level:
    org.springframework.security: INFO

# Platform Servers
hspc:
  platform:
    api:
      security:
        # determines if security is applied at the contextPath
        mode: secured
#        mode: mock
#        mode: open
      oauth2:
        clientId: hspc_resource_server
        clientSecret: secret
        scopes: openid,launch,smart/orchestrate_launch
      sandbox:
        name: hspc5
      fhir:
        db:
          schema: hspc_5_${hspc.platform.api.sandbox.name}
          driver-class-name: com.mysql.jdbc.Driver
          host: localhost
          url: jdbc:mysql://${hspc.platform.api.fhir.db.host}:3306/${hspc.platform.api.fhir.db.schema}
          username: root
          password: password
        datasource:
          cache:
            size: 40
        defaultTenantId: ${hspc.platform.api.sandbox.name}
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
        terminology:
          proxy:
            host: api-v5-stu3.hspconsortium.org/term01
            contextPath: /open
        federatedEndpointURL: dataphoria.org/datafhir
        contextPath: data
        # remove openContextPath to disable the open endpoint
        openContextPath: open
    authorization:
      protocol: http
      host: localhost
      port: 8060
      context: ~
      url: ${hspc.platform.authorization.protocol}://${hspc.platform.authorization.host}:${hspc.platform.authorization.port}${hspc.platform.authorization.context}
#      url: https://auth.hspconsortium.org/
      authorizeUrl: ${hspc.platform.authorization.url}/authorize
      tokenUrl: ${hspc.platform.authorization.url}/token
#      authorizeUrl: ${hspc.platform.authorization.url}/mock/authorize
#      tokenUrl: ${hspc.platform.authorization.url}/mock/token
      tokenCheckUrl: ${hspc.platform.authorization.url}/introspect
      userinfoUrl: ${hspc.platform.authorization.url}/userinfo
      smart:
        launchUrl: ${hspc.platform.authorization.url}/Launch
        registrationEndpointUrl: ${hspc.platform.authorization.url}/register
        urisEndpointExtensionUrl: http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris
        launchRegistrationUrl: /${hspc.platform.api.fhir.contextPath}/_services/smart/Launch
    messaging:
      protocol: http
      host: localhost
      port: 8091
      context: /
      url: ${hspc.platform.messaging.protocol}://${hspc.platform.messaging.host}:${hspc.platform.messaging.port}${hspc.platform.messaging.context}
      subscriptionSupport:
        enabled: false
        subscriptionEndpoint: ${hspc.platform.messaging.url}/subscription
        resourceEndpoint: ${hspc.platform.messaging.url}/resource

---

spring:
  profiles: dstu2

hspc:
  platform:
    api:
      sandbox:
        name: dstu2

---

spring:
  profiles: stu3

hspc:
  platform:
    api:
      sandbox:
        name: stu3