server:
  port: 8076

hibernate:
  search:
    default:
      indexBase: /var/indexes/@artifact.name@

# Platform Servers
hspc:
  platform:
    api:
      oauth2:
        clientSecret: secret
      fhir:
        db:
          host: sandboxdb.hspconsortium.org
          username: system
          password: ENC(lA/Ifn1Cm6pYGGydIXNQIa6n7ryn5A1+)
        terminology:
          proxy:
            host: api-v5-stu3.hspconsortium.org/${hspc.platform.api.sandbox.name}
            contextPath: /open
    authorization:
      url: https://auth.hspconsortium.org
    messaging:
      protocol: http
      subscriptionSupport:
        enabled: false

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES