# Platform Servers
hspc:
  platform:
    api:
      oauth2:
        clientSecret: secret
      fhir:
        db:
          host: db-test.hspconsortium.org
          password: ENC(PGbAqA2yTasSehiLRk60NpQLMQ1btRtID+8hvhWf9AI=)
        datasource:
          cache:
            size: 5
        terminology:
          proxy:
            host: api-v5-stu3.hspconsortium.org/${hspc.platform.api.sandbox.name}
            contextPath: /open
    authorization:
      url: https://auth-test.hspconsortium.org
    messaging:
      protocol: http
      host: messaging-test.hspconsortium.org
      subscriptionSupport:
        enabled: false

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES
