spring:
  profiles:
    active: multitenant,production,stu3,mock

hspc:
  platform:
    authorization:
      url: http://localhost:8080/hspc-reference-authorization-mock
    messaging:
      subscriptionSupport:
        enabled: true