spring:
  profiles:
    active: multitenant,production,stu3,persona

hspc:
  platform:
    authorization:
      url: http://localhost:8080/hspc-reference-authorization-persona
    messaging:
      subscriptionSupport:
        enabled: true