# Platform Servers
hspc:
  platform:
    api:
      oauth2:
        clientSecret: secret
      fhir:
        db:
          host: sandboxdb-test.hspconsortium.org
          username: system
          password: ENC(H5tJdn4wTllfyqSkrkmzRNQNhwl7AZhB)
        datasource:
          cache:
            size: 5
    authorization:
      url: https://auth-test.hspconsortium.org
    messaging:
      pubsub:
        enabled: true
        forSandboxes: travisdstu2
        subscription:
          channel:
            endpoint: http://pubsub.hspconsortium.org:9002/fhir-subscription/publish
#          forResources: Patient,Observation,Allergy

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES

---

spring:
  profiles: dstu2

hibernate:
  search:
    default:
      indexBase: /var/indexes/@artifact.name@/dstu2

---

spring:
  profiles: stu3

hibernate:
  search:
    default:
      indexBase: /var/indexes/@artifact.name@/stu3
