# Platform Servers
hspc:
  platform:
    api:
      oauth2:
        clientSecret: secret
      fhir:
        db:
          host: sandboxdb-test.hspconsortium.org
          username: hspctest
          password: ENC(kYqZKAjsHHSeqTtyGKzNsrrIUWdjXiXl)
        datasource:
          cache:
            size: 5
    authorization:
      url: https://auth-test.hspconsortium.org

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES

---

spring:
  profiles: dstu2

hibernate:
  search:
    default:
      indexBase: /var/indexes/@artifact.name@/dstu2

---

spring:
  profiles: stu3

hibernate:
  search:
    default:
      indexBase: /var/indexes/@artifact.name@/stu3
