# Platform Servers
hspc:
  platform:
    api:
      oauth2:
        clientSecret: secret
      fhir:
        db:
          host: sandboxdb.hspconsortium.org
          username: system
          password: ENC(rTXsi4FKX55cPv6RBcVl6bcSxoUmECl+)
    authorization:
      url: https://auth.hspconsortium.org

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES

---

spring:
  profiles: dstu2

hspc:
  platform:
    api:
      fhir:
        hibernate:
          indexSourceUrl: https://content.hspconsortium.org/datasets/reference-api/hspc_5/indexes_hspc_5_dstu2.tar.gz

hibernate:
  search:
    default:
      indexBase: /var/indexes/@artifact.name@/dstu2

---

spring:
  profiles: stu3

hspc:
  platform:
    api:
      fhir:
        hibernate:
          indexSourceUrl: https://content.hspconsortium.org/datasets/reference-api/hspc_5/indexes_hspc_5_stu3.tar.gz

hibernate:
  search:
    default:
      indexBase: /var/indexes/@artifact.name@/stu3
