server:
  port: 8070

spring:
  application:
    name: HSPC Reference API
  jmx:
    enabled: false
  profiles:
    active: multitenant,stu3
#    active: multitenant,stu3,globalexception
  resources:
    chain:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      show_sql: false
      format_sql: true
  datasource:
    initialSize: 1
    maxActive: 5
    maxActive: 10

hibernate:
  search:
    default:
      indexBase: target/@artifact.name@/lucenefiles

logging:
  level:
    org.springframework.security: INFO

# Platform Servers
hspc:
  platform:
    api:
      security:
        # determines if security is applied at the contextPath
        mode: secured
#        mode: mock
#        mode: open
      oauth2:
        clientId: hspc_resource_server
        clientSecret: secret
        scopes: openid,launch,smart/orchestrate_launch
      sandbox:
        name: hspc4
        useHspcStarterData: true
      fhir:
        db:
          schema: hspc_4_${hspc.platform.api.sandbox.name}
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/${hspc.platform.api.fhir.db.schema}
          username: root
          password: password
        defaultTenantId: ${hspc.platform.api.sandbox.name}
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        terminology:
          proxy:
            host: fhir3.healthintersections.com.au
            contextPath: /open
        federatedEndpointURL: dataphoria.org/datafhir
        contextPath: data
        # remove openContextPath to disable the open endpoint
        openContextPath: open
    authorization:
      url: http://localhost:8080/hspc-reference-authorization
      authorizeUrl: ${hspc.platform.authorization.url}/authorize
      tokenUrl: ${hspc.platform.authorization.url}/token
#      authorizeUrl: ${hspc.platform.authorization.url}/mock/authorize
#      tokenUrl: ${hspc.platform.authorization.url}/mock/token
      tokenCheckUrl: ${hspc.platform.authorization.url}/introspect
      userinfoUrl: ${hspc.platform.authorization.url}/userinfo
      smart:
        launchUrl: ${hspc.platform.authorization.url}/Launch
        registrationEndpointUrl: ${hspc.platform.authorization.url}/register
        urisEndpointExtensionUrl: http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris
    messaging:
      url: http://localhost:8080/hspc-reference-messaging
      subscriptionSupport:
        enabled: false
        subscriptionEndpoint: ${hspc.platform.messaging.url}/subscription
        resourceEndpoint: ${hspc.platform.messaging.url}/resource