# Platform Servers
hspc:
  platform:
    api:
      oauth2:
        clientSecret: secret
      fhir:
        datasource:
          host: sandboxdb-test.hspconsortium.org
          username: system
          password: ENC(H5tJdn4wTllfyqSkrkmzRNQNhwl7AZhB)
          cache:
            size: 5
      sandboxManagerApi:
        url: https://${SBMA_HOST:sandbox-api-test.hspconsortium.org}
        transactionPath: /analytics/transaction
    authorization:
      url: https://auth-test.hspconsortium.org
    messaging:
      pubsub:
        enabled: true
        forSandboxes: travisdstu2,PulmonaryEmbolismDSTU2,noman_dstu2,nomanstu3,nomandstu2
        subscription:
          channel:
            endpoint: http://pubsub.hspconsortium.org:9002/fhir-subscription/publish
        includeSourceQueryParameter: true

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES

---

spring:
  profiles: dstu2

hibernate:
  search:
    default:
      indexBase: /var/indexes/@artifact.name@/dstu2

---

spring:
  profiles: stu3

hibernate:
  search:
    default:
      indexBase: /var/indexes/@artifact.name@/stu3

---

smart-configuration-metadata:
  authorization_endpoint: "https://auth-test.hspconsortium.org/authorize"
  token_endpoint: "https://auth-test.hspconsortium.org/token"
  token_endpoint_auth_methods_supported: ["client_secret_basic"]
  registration_endpoint: "https://auth-test.hspconsortium.org/register"
  scopes_supported: ["smart/orchestrate_launch",
                     "launch",
                     "openid",
                     "profile",
                     "user/*.*",
                     "user/*.read",
                     "user/*.write",
                     "user/AdverseReaction.read",
                     "user/AdverseReaction.write",
                     "user/Alert.read",
                     "user/Alert.write",
                     "user/Condition.read",
                     "user/Condition.write",
                     "user/Encounter.read",
                     "user/Encounter.write",
                     "user/FamilyHistory.read",
                     "user/FamilyHistory.write",
                     "user/Medication.read",
                     "user/Medication.write",
                     "user/MedicationPrescription.read",
                     "user/MedicationPrescription.write",
                     "user/MedicationStatement.read",
                     "user/MedicationStatement.write",
                     "user/Observation.read",
                     "user/Observation.write",
                     "user/Patient.read",
                     "user/Patient.write",
                     "user/Substance.read",
                     "user/Substance.write",
                     "patient/*.*",
                     "patient/*.read",
                     "patient/*.write",
                     "patient/AdverseReaction.read",
                     "patient/AdverseReaction.write",
                     "patient/Alert.read",
                     "patient/Alert.write",
                     "patient/Condition.read",
                     "patient/Condition.write",
                     "patient/Encounter.read",
                     "patient/Encounter.write",
                     "patient/FamilyHistory.read",
                     "patient/FamilyHistory.write",
                     "patient/MedicationPrescription.read",
                     "patient/MedicationPrescription.write",
                     "patient/MedicationStatement.read",
                     "patient/MedicationStatement.write",
                     "patient/Observation.read",
                     "patient/Observation.write",
                     "patient/Patient.read",
                     "patient/Patient.write",
                     "system/*.read",
                     "system/*.write",
                     "launch/patient",
                     "launch/encounter",
                     "launch/location",
                     "patient/AllergyIntolerance.read",
                     "patient/AllergyIntolerance.write",
                     "user/AllergyIntolerance.read",
                     "user/AllergyIntolerance.write",
                     "patient/DocumentReference.read",
                     "patient/DocumentReference.write",
                     "online_access",
                     "user/Immunization.read",
                     "user/Immunization.write",
                     "user/MedicationOrder.read",
                     "user/MedicationOrder.write",
                     "patient/Immunization.read",
                     "patient/Immunization.write",
                     "patient/MedicationOrder.read",
                     "patient/MedicationOrder.write",
                     "offline_access",
                     "fhirUser"]
  response_types_supported: ["code"]
  management_endpoint: "https://auth-test.hspconsortium.org/manage"
  introspection_endpoint: "https://auth-test.hspconsortium.org/introspect"
  revocation_endpoint: "https://auth-test.hspconsortium.org/revoke"
  capabilities: ["launch-ehr", "client-public", "client-confidential-symmetric", "context-ehr-patient", "sso-openid-connect", "launch-standalone"]
