# Platform Servers
hspc:
  platform:
    api:
      oauth2:
        clientSecret: secret
      fhir:
        datasource:
          host: sandboxdb-test.hspconsortium.org # sandboxdb-test.logicahealth.org
          username: system
          password: ENC(H5tJdn4wTllfyqSkrkmzRNQNhwl7AZhB)
          cache:
            size: 5
      sandboxManagerApi:
        url: https://${SBMA_HOST:sandbox-api-test.hspconsortium.org}  # https://${SBMA_HOST:sandbox-api-test.logicahealth.org}
        transactionPath: /analytics/transaction
    authorization:
      url: https://auth-test.hspconsortium.org  # https://auth-test.logicahealth.org
    messaging:
      pubsub:
        enabled: true
        forSandboxes: travisdstu2,PulmonaryEmbolismDSTU2,noman_dstu2,nomanstu3,nomandstu2
        subscription:
          channel:
            endpoint: http://pubsub.hspconsortium.org:9002/fhir-subscription/publish # http://pubsub.logicahealth.org:9002/fhir-subscription/publish
        includeSourceQueryParameter: true

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES

---

spring:
  profiles: dstu2

hibernate:
  search:
    default:
      indexBase: /var/indexes/@artifact.name@/dstu2

---

spring:
  profiles: stu3

hibernate:
  search:
    default:
      indexBase: /var/indexes/@artifact.name@/stu3

