# Platform Servers
hspc:
  platform:
    api:
      security:
        # determines if security is applied at the contextPath
#        mode: secured
        mode: mock
#        mode: open
    authorization:
      port: ${AUTH_PORT:8260}
