# Platform Servers
hspc:
  platform:
    api:
      oauth2:
        clientSecret: secret
      fhir:
        db:
          host: sandboxdb.hspconsortium.org
          username: system
          password: ENC(PN5w0Ds+k3I2vOVS/dZM/N9HaIFZgGIX)
      sandboxManagerApi:
        url: https://${SBMA_HOST:sandbox-api.hspconsortium.org}
        transactionPath: /analytics/transaction
    authorization:
      url: https://auth.hspconsortium.org
    messaging:
      pubsub:
        enabled: true
        forSandboxes: travisdstu2,PulmonaryEmbolismDSTU2,noman_dstu2,nomanstu3,nomandstu2,PulmonaryEmbolism2,PulmonaryEmbolismVer
        subscription:
          channel:
            endpoint: http://pubsub.hspconsortium.org:9002/fhir-subscription/publish
        includeSourceQueryParameter: true

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES

---

spring:
  profiles: dstu2

hspc:
  platform:
    api:
      fhir:
        hibernate:
          indexSourceUrl: https://content.hspconsortium.org/datasets/reference-api/hspc_5/indexes_hspc_5_dstu2.tar.gz

hibernate:
  search:
    default:
      indexBase: /var/indexes/@artifact.name@/dstu2

---

spring:
  profiles: stu3

hspc:
  platform:
    api:
      fhir:
        hibernate:
          indexSourceUrl: https://content.hspconsortium.org/datasets/reference-api/hspc_5/indexes_hspc_5_stu3.tar.gz

hibernate:
  search:
    default:
      indexBase: /var/indexes/@artifact.name@/stu3
